services:
  web:
    image: ghcr.io/sinu5oid/server:${GIT_COMMIT_HASH:-latest}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.web.loadbalancer.server.port=8080"
      - "traefik.http.routers.web.rule=Host(`meowlab.tech`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.middlewares=test-compress"
      - "traefik.docker.network=proxy-swarm"
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.middlewares.test-compress.compress=true"
    networks:
      - proxy-swarm
    deploy:
      update_config:
        order: start-first

networks:
  proxy-swarm:
    external: true
